name: Scheduled Jobs

on:
 schedule:
   - cron: '0 0 * * *'
 workflow_dispatch:

jobs:
 test_schedule:
   runs-on: ubuntu-latest
   steps:
     - name: echo repository name
       run: echo "${{ github.repository }}"

     - name: repository checkout
       uses: actions/checkout@v2
       with:
         repository: ${{ github.repository }}
         token: ${{ secrets.MY_GITHUB_TOKEN }}
         path: workflows

     - name: Add date and push
       run: |
         cd workflows
         date >> date.txt
         git add .
         git config --global user.email "donghalim7@gmail.com"
         git config --global user.name "Dongha Lim"
         git commit -am "Inject Date"
         git push
